name: Test

on:
  pull_request:
    paths:
      - "**.json"
      - "**.ts"
      - "**.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
